### ISSUE TITLE
TypeError: error.annotate is not a function

### ISSUE THREAD

**Issue by tnelson-doghouse** [mobilenations/newrelic_cloudflare#2]
My setup isn't working except the Railgun part (which shows the fault is probably in the part that talks to Cloudflare, not the New Relic or Railgun parts).  The error log is full of this message:

```
TypeError: error.annotate is not a function
    at /home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/cloudflare4/index.js:179:27
    at tryCatcher (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
It seems to me the error is in the cloudflare4 module, which is from https://github.com/icodeforlove/node-cloudflare and was last updated December 5 2018.  I note that there are a lot of other cloudflare modules, including https://github.com/cloudflare/node-cloudflare that was updated yesterday (and may even be cloudflare official; not sure, but worth a check).  I'm not sure what the compatibility is like, but would it be more useful to use this instead, if the cloudflare4 one is a problem?  

Any help or advice appreciated!

**Comment by tnelson-doghouse** [comment]
The error above was in the error log.  The output log also has this:

```
TypeError: Cannot read property 'query' of undefined
    at instance._tryRequest (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/cloudflare4/index.js:91:38)
    at instance._paginateRequest (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/cloudflare4/index.js:190:8)
    at instance._paginateRequest (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/promise-object/index.js:78:11)
    at /home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/cloudflare4/index.js:170:30
    at tryCatcher (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ec2-user/cloudflare-plugin/newrelic_cloudflare-master/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
```

**Comment by reyesvindas** [comment]
I'm seeing the same exact errors when executing the getZoneIDs() function.

I'm seeing the dashboard in New Relic but due to this error is not been populated.

**Comment by tnelson-doghouse** [comment]
Same.

**Comment by ttk** [comment]
Seems like the node-cloudflare dependency isn't compatible with newer versions of node/npm.  I've successfully used:
```
node -v
v9.11.2

npm -v
5.6.0
```
